services:
  npm:
    image: node:22-alpine
    working_dir: /app
    volumes:
      - .:/app
    command: "npm run build"

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    working_dir: /code
    volumes:
      - ./:/code
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    environment:
      POSTGRES_DB: recipes
      POSTGRES_PASSWORD: password
      POSTGRES_USER: recipes
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "recipes", "-U", "recipes"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - database_data:/var/lib/postgresql/data:rw
    ports:
        - "5432:5432"

  php:
    image: php:8.3-fpm-alpine
    working_dir: /code
    volumes:
      - ./:/code
    command: >
      sh -c "
      chown -R www-data:www-data var &&
      chmod -R 775 var &&
      php-fpm
      "

volumes:
  database_data:

