services:
  npm:
    image: node:22-alpine
    working_dir: /code
    volumes:
      - .:/code
    command: sh -c "npm install && npm run build"

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    working_dir: /code
    volumes:
      - ./:/code
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    environment:
      POSTGRES_DB: recipes
      POSTGRES_PASSWORD: password
      POSTGRES_USER: recipes
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "recipes", "-U", "recipes"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - database_data:/var/lib/postgresql/data:rw
    ports:
        - "5432:5432"

  php:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /code
    volumes:
      - ./:/code
    ports:
      - "9000:9000" # Si nécessaire pour PHP-FPM

volumes:
  database_data:

